Update home.tpl
CodeForPhilly/codeforphilly.org pull request #101
Opened 2023-06-13 23:45 UTC by andriacooper

Added homepage tile for Balancer project and project details.

2024-03-05 19:57 UTC, themightychris approved these changes

2024-04-02 14:07 UTC, themightychris requested changes
there's a parameter error in the new projcet

2024-10-22 00:23 UTC, travissouthard commented
Hi @themightychris! Can you take a look and test this? I updated our current projects to be up to date and _believe_ I fixed the parameter error mentioned above

2024-11-13 00:42 UTC, travissouthard commented
Okay cool, I also added our Insta link to the social links. Ready and a half

2024-11-13 01:05 UTC, merged